### ISSUE TITLE
End of Line Sequence breaks entrypoint.sh file when it needs to be executed in the container

### ISSUE THREAD

**Issue by undercontr** [unoconv/unoserver-docker#7] opened 2023-04-20 07:12 UTC
Hello,

It seems the end of line sequence of entrypoint.sh file is breaking the ENTRYPOINT execution in the Dockerfile

The error is: `/config/entrypoint.sh: set: line 2: illegal option -`
Error is throwing because the end of lines are not properly recognized by bash. Linux wants to have a LF ending but entrypoint.sh lines ending with CRLF.

To fix this error I used **dos2unix** tool to convert CRLF end of lines to LF end of lines.

**Comment by jimisola** [comment] 2023-04-21 21:40
1. What system are you trying to build the image on? 
2. Have you used the pre-built image?

**Comment by undercontr** [comment] 2023-04-21 22:03
Hey Jimisola, 

1. I'm using Docker in Windows 11 with WSL enabled and the version is 20.10.23, build 7155243. 
2. I didn't used the pre-built image, I explicitly wanted to built the image to see the building process and what Dockerfile does to the image to create such Libreoffice instance and call it with UNO.

Sorry for missing information

**Comment by jimisola** [comment] 2023-04-21 22:24
Ok. No worries. It's just that I won't be able to reproduce the issue that you have on Windows with WSL.
I'm not a Windows user myself when it comes developing.

When I run dos2unix on the Dockerfile locally on Ubuntu 22.04 the file does not change. I'm using VS Code.
Could it be that your line endings are changed when you checkout the code or something like?

**Comment by jimisola** [comment] 2023-04-22 21:54
Am I understanding you right that the #6 does not contain the dos2unix cleanup?
Would you mind creating a PR where you have ran dos2unix on Dockerfile?
I would like to see what changes there are to file.

**Comment by undercontr** [comment] 2023-04-26 19:54
Hello, sorry for the late reply here was busy with work.

Yes the PR has no fix for the line endings, only for Dockerfile, it seems git doesn't recognize if line endings are LF or CRLF. It considers no change made to the file, hence it won't be committed. That's what happened after dos2unix cleanup.

I'm using Windows version of Docker for building images and creating containers. Not a Docker installation inside the WSL. Probably that's why it's not reproduceable in all cases.

**Comment by jimisola** [comment] 2023-05-05 19:03
No worries. Busy here with work, studies and preps for moving to a new home.

I can't reproduce the CRLF. As far as I can see line endings are LFs everywhere.

**Comment by jimisola** [comment] 2023-05-12 00:34
Alpine 3.18 has been released now. I've made some changes (see #10).

Feel to test. It's on branch https://github.com/unoconv/unoserver-docker/tree/10-verify-that-pyuno-path-is-set-correctly-with-alpine-318-and-libreoffice-7441-and-then-remove-workaround

**Comment by jimisola** [comment] 2024-01-14 18:09
@undercontr Are you still experiencing this issue? I'm closing it now but will reopen if so.

**Closed by jimisola** 2024-01-14 18:09 UTC
